services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on: [db]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
