services:
  api:
    build: ./platform-api
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: frontend
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - ./data_examples:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

