 name: API CI

 on:
   push:
     branches: ["main"]
   pull_request:
     branches: ["main"]

 jobs:
   build:
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: ./platform-api

     steps:
       - uses: actions/checkout@v4
       - name: Setup java
         uses: actions/setup-java@v2
         with:
           distribution: 'temurin'
           java-version: '21'
           java-package: jdk

       - name: Build app
         run: mvn clean compile

       - name: Run Tests
         run: mvn clean test